  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: samarium_app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_DATABASE=samarium
      - DB_USERNAME=samarium_user
      - DB_PASSWORD=samarium_password
    volumes:
      - laravel-storage:/var/www/html/storage
      - laravel-cache:/var/www/html/bootstrap/cache
      - ./:/var/www/html
      - /var/www/html/node_modules
      - /var/www/html/vendor
    entrypoint: ["/var/www/html/docker-entrypoint.sh"]
    depends_on:
      - db
    networks:
      - laravel-network
